### ISSUE TITLE
some billable services dont load the service costs on the cashier view 

### ISSUE THREAD

**Issue by ndisha** [bespokeinteractive/billing#7]
There seems to be an issue with some billable services e.g. the Radiology ones. They have a cost in the admin panel as can be seen below:
<img width="511" alt="screen shot 2015-12-03 at 10 08 02 am" src="https://cloud.githubusercontent.com/assets/801106/11554204/fdc5c2ac-99a6-11e5-8195-3b23c8524a8b.png">
However, on the cashier view, they are displayed with a 0 cost, see below:
<img width="1268" alt="screen shot 2015-12-03 at 10 08 20 am" src="https://cloud.githubusercontent.com/assets/801106/11554211/14ee6ad8-99a7-11e5-93c1-d87e70d44cca.png">

@bkirui tells me its an issue with concepts and for sure it is since I can view the radiology concepts, I get the following error:
<img width="538" alt="screen shot 2015-12-03 at 10 14 51 am" src="https://cloud.githubusercontent.com/assets/801106/11554230/2a7ebcf4-99a7-11e5-8ed0-a291c8b4f807.png">

We need to check into this @geoff-wasilwa.

**Comment by bkirui** [comment]
@ndisha Issue in billing for radiology department has been sorted, added radiology department under manage department in Administrator and specified the investigations

**Comment by ndisha** [comment]
@bkirui, this seems to be fixed! 
![1f44d](https://cloud.githubusercontent.com/assets/801106/11556414/734899d6-99b7-11e5-9608-b4b2b2225ad9.png)
Closing!
